#generated by AI and this is AI copy

# ============================================================
# TEACHER STUDENT REPORT GENERATOR
# ============================================================
#
# This program allows teachers to create student reports
# containing:
#
# - Student name
# - MEG (Minimum Expected Grade)
# - Predicted grade
# - Attitude to Learning
# - Homework
# - Teacher comments
#
# Replace the values marked [enter ...] with your own data.
# ============================================================


# ------------------------------------------------------------
# STUDENT DATA
# ------------------------------------------------------------
#
# Add as many students as you need.
#
# Example:
#
# {
#     "name": "[enter name]",
#     "meg": "[enter MEG]",
#     "predicted_grade": "[enter predicted grade]",
#     "attitude": "[enter attitude to learning]",
#     "homework": "[enter homework]",
#     "comment": "[enter teacher comment]"
# }
#
# ------------------------------------------------------------

students = [

    {
        "name": "Nick",
        "meg": "4",
        "predicted_grade": "6",
        "attitude": "Excelent",
        "homework": "Excelent",
        "comment": "this student is doing way more then what I expect in my lesson. keep up with the good work!"
    },

    {
        "name": "David",
        "meg": "5",
        "predicted_grade": "3",
        "attitude": "Requires Significant Improvement",
        "homework": "Requires Impovement",
        "comment": "This student is not reaching his full protential in lessons, much needed improvement is nessary for him to succeed and get the greades he want"
    },

    {
        "name": "Ava",
        "meg": "6",
        "predicted_grade": "7",
        "attitude": "Good",
        "homework": "Excellent",
        "comment": "Student does really well in this subject however se can improve on some aspects to make her greades better for her GCSE's"
    },


]
#DEMO DATA NOTICE All names, grades, comments, and other student information displayed in this demonstration are entirely fictional and have been created for demonstration purposes only.

#Any resemblance to actual persons, living or deceased, is purely coincidental.

# ------------------------------------------------------------
# DISPLAY A SINGLE REPORT
# ------------------------------------------------------------

def display_report(student):

    print("\n")
    print("=" * 60)
    print("                    STUDENT REPORT")
    print("=" * 60)

    print("Student:", student["name"])
    print()

    print("MEG:", student["meg"])
    print("Predicted Grade:", student["predicted_grade"])
    print("Attitude to Learning:", student["attitude"])
    print("Homework:", student["homework"])

    print()
    print("Teacher Comment:")
    print(student["comment"])

    print("=" * 60)


# ------------------------------------------------------------
# DISPLAY ALL REPORTS
# ------------------------------------------------------------

def display_all_reports():

    print("\n")
    print("=" * 60)
    print("                 ALL STUDENT REPORTS")
    print("=" * 60)

    for student in students:

        display_report(student)


# ------------------------------------------------------------
# FIND A STUDENT
# ------------------------------------------------------------

def find_student():

    name = input("\nEnter the student's name: ")

    found = False

    for student in students:

        if student["name"].lower() == name.lower():

            display_report(student)
            found = True
            break

    if not found:

        print("\nStudent not found.")


# ------------------------------------------------------------
# ADD A NEW STUDENT
# ------------------------------------------------------------

def add_student():

    print("\n")
    print("=" * 60)
    print("                 ADD NEW STUDENT")
    print("=" * 60)

    name = input("Student name: ")
    meg = input("MEG: ")
    predicted_grade = input("Predicted grade: ")
    attitude = input("Attitude to Learning: ")
    homework = input("Homework: ")
    comment = input("Teacher comment: ")

    new_student = {
        "name": name,
        "meg": meg,
        "predicted_grade": predicted_grade,
        "attitude": attitude,
        "homework": homework,
        "comment": comment
    }

    students.append(new_student)

    print("\nStudent successfully added.")


# ------------------------------------------------------------
# MAIN MENU
# ------------------------------------------------------------

def main():

    while True:

        print("\n")
        print("=" * 60)
        print("              TEACHER REPORT SYSTEM - DEMO")
        print("=" * 60)

        print()
        print("Version 1.1 Demo edition")
        print("(c) BlueSnake 2026, program is open source")
        print()
        
        print("DEMO DATA NOTICE")
        print()
        print("All names, grades, comments, and other student information")
        print("displayed in this demonstration are entirely fictional")
        print("and have been created for demonstration purposes only.")
        print()
        print("Any resemblance to actual persons, living or deceased,")
        print("is purely coincidental.")
        print()

        print("1. View all reports")
        print("2. Find a student")
        print("3. Add a student")
        print("4. Exit")

        choice = input("\nSelect an option: ")

        if choice == "1":

            display_all_reports()

        elif choice == "2":

            find_student()

        elif choice == "3":

            add_student()

        elif choice == "4":

            print("\nExiting report system...")
            break

        else:

            print("\nInvalid option.")
            print("Please choose 1, 2, 3 or 4.")


# ------------------------------------------------------------
# START PROGRAM
# ------------------------------------------------------------

main()
